# Generated by Django 4.2.27 on 2026-01-30 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_chatroom_church_chatroom_location_chatroom_room_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='banner',
            field=models.ImageField(blank=True, null=True, upload_to='banners/'),
        ),
    ]
