# koyeb.yaml - Koyeb Service Configuration
services:
  - name: harvestconnect-backend
    type: web
    docker:
      build:
        context: .
        dockerfile: backend/Dockerfile
      args:
        - CACHEBUST={{timestamp}}
    env:
      - name: DEBUG
        value: "false"
      - name: DJANGO_SECRET_KEY
        secret: DJANGO_SECRET_KEY
      - name: DATABASE_URL
        secret: DATABASE_URL
      - name: ALLOWED_HOSTS
        value: "localhost,127.0.0.1,0.0.0.0,desperate-swan-oludayoadeoye-56108851.koyeb.app"
      - name: CORS_ALLOWED_ORIGINS
        value: "http://localhost:3000,http://localhost:3001,http://127.0.0.1:3000,https://desperate-swan-oludayoadeoye-56108851.koyeb.app,https://desperate-swan-oludayoadeoye-56108851.koyeb.app:443"
      - name: CSRF_TRUSTED_ORIGINS
        value: "http://localhost:8000,http://localhost:3000,https://desperate-swan-oludayoadeoye-56108851.koyeb.app,https://desperate-swan-oludayoadeoye-56108851.koyeb.app:443"
      - name: EMAIL_BACKEND
        value: "django.core.mail.backends.smtp.EmailBackend"
      - name: EMAIL_HOST
        value: "smtp.gmail.com"
      - name: EMAIL_PORT
        value: "587"
      - name: EMAIL_USE_TLS
        value: "true"
      - name: EMAIL_HOST_USER
        secret: EMAIL_HOST_USER
      - name: EMAIL_HOST_PASSWORD
        secret: EMAIL_HOST_PASSWORD
      - name: GOOGLE_OAUTH2_CLIENT_ID
        secret: GOOGLE_OAUTH2_CLIENT_ID
      - name: GOOGLE_OAUTH2_CLIENT_SECRET
        secret: GOOGLE_OAUTH2_CLIENT_SECRET
      - name: GITHUB_OAUTH2_CLIENT_ID
        secret: GITHUB_OAUTH2_CLIENT_ID
      - name: GITHUB_OAUTH2_CLIENT_SECRET
        secret: GITHUB_OAUTH2_CLIENT_SECRET
      - name: STRIPE_PUBLISHABLE_KEY
        secret: STRIPE_PUBLISHABLE_KEY
      - name: STRIPE_SECRET_KEY
        secret: STRIPE_SECRET_KEY
      - name: STRIPE_WEBHOOK_SECRET
        secret: STRIPE_WEBHOOK_SECRET
    routes:
      - path: /
        port: 8000
    ports:
      - port: 8000
        protocol: http
    health_checks:
      http:
        path: /health/
        interval: 30
        timeout: 10
        healthy_threshold: 1
        unhealthy_threshold: 3
